<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HalmolenCA.Application\HalmolenCA.Application.csproj" />
    <ProjectReference Include="..\HalmolenCA.Domain\HalmolenCA.Domain.csproj" />
  </ItemGroup>

</Project>
